---
title: "git_00"
author: "Ixcell Espinoza- Alvarado"
date: "Feb 2024"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```
# Build a Poem with a sequence of commits to the master branch.
Our project will be done using several commits to the master branch.
<!-- Do not modify or change any text in "!--" bracketed areas such as this --- these are instructions to
you, if you change any of this the git program will notice it and compromise your git merging strategy !-->

## First Verse 
<!--Put the first five lines of a poem by Lewis Carrol in this section!-->

There was an ancient City, stricken down

With a strange frenzy, and for many a day

They paced from morn to eve the crowded town,

And danced the night away.

I asked the cause: the aged man grew sad:

## Second Verse
<!--Put the first five lines of a poem by Robert Frost here!-->

Two roads diverged in a yellow wood,

And sorry I could not travel both

And be one traveler, long I stood

And looked down one as far as I could

To where it bent in the undergrowth;

## Third Verse
<!--Put the first two verses of The Walrus and the Carpenter here!-->

  "The sun was shining on the sea,
     
  Shining with all his might:

## Last Verse
<!--Put a short poem of your choice 8-20 lines,here!-->

Once upon a midnight dreary, while I pondered, weak and weary,

Over many a quaint and curious volume of forgotten lore,

While I nodded, nearly napping, suddenly there came a tapping,

As of some one gently rapping, rapping at my chamber door. “

“'Tis some visitor,” I muttered, “tapping at my chamber door—

Only this, and nothing more.”

Ah, distinctly I remember it was in the bleak December,

And each separate dying ember wrought its ghost upon the floor.

Eagerly I wished the morrow;—vainly I had sought to borrow

From my books surcease of sorrow—sorrow for the lost Lenore—

For the rare and radiant maiden whom the angels name Lenore—

Nameless here for evermore.
